openapi: 3.0.3
info:
  title: Hono Chat Module API
  description: API documentation for the Hono Chat Module with rich sample data.
  version: 1.0.0
servers:
  - url: http://localhost:3099
    description: Local Development Server

components:
  securitySchemes:
    UserIdHeader:
      type: apiKey
      in: header
      name: x-user-id
      description: User ID for authentication (Mock)
    AppIdHeader:
      type: apiKey
      in: header
      name: x-app-id
      description: Application ID for authentication (Mock)

  schemas:
    # --- Payloads ---
    ConnectPayload:
      type: object
      required:
        - app_id
        - user_id
      properties:
        app_id:
          type: string
          example: "my_chat_app"
        user_id:
          type: string
          example: "alice_123"
        name:
          type: string
          example: "Alice Wonderland"
        device_token:
          type: string
          example: "fcm_token_1234567890"
        device_type:
          type: string
          enum: [android, ios, web]
          example: "ios"

    CreateConversationPayload:
      type: object
      required:
        - type
        - participant_ids
      properties:
        type:
          type: string
          enum: [DIRECT, GROUP]
          example: "GROUP"
        participant_ids:
          type: array
          items:
            type: string
          example: ["bob_456", "charlie_789"]
        name:
          type: string
          description: Optional name for group chats
          example: "Project X Team"

    SendMessagePayload:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum: [TEXT, IMAGE, DOCUMENT, AUDIO, CALL]
          example: "TEXT"
        content:
          type: string
          example: "Hey team, when is the next meeting?"
        metadata:
          type: object
          additionalProperties: true
          example: { "priority": "high" }

    AddParticipantPayload:
      type: object
      required:
        - user_ids
      properties:
        user_ids:
          type: array
          items:
            type: string
          example: ["dave_101"]

    UploadResponse:
      type: object
      properties:
        url:
          type: string
          example: "/uploads/1705678900000_image.png"

    # --- Responses ---
    User:
      type: object
      properties:
        id:
          type: string
          example: "my_chat_app_alice_123"
        appId:
          type: string
          example: "my_chat_app"
        userId:
          type: string
          example: "alice_123"
        name:
          type: string
          example: "Alice Wonderland"
        deviceToken:
          type: string
          example: "fcm_token_1234567890"
        deviceType:
          type: string
          example: "ios"
        lastSeen:
          type: string
          format: date-time
          example: "2024-01-19T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-19T10:30:00Z"

    Conversation:
      type: object
      properties:
        id:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        appId:
          type: string
          example: "my_chat_app"
        type:
          type: string
          enum: [DIRECT, GROUP]
          example: "GROUP"
        name:
          type: string
          nullable: true
          example: "Project X Team"
        adminId:
          type: string
          example: "my_chat_app_alice_123"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-19T12:00:00Z"
        lastMessage:
          $ref: '#/components/schemas/Message'
          nullable: true
        unreadCount:
          type: number
          example: 2

    Message:
      type: object
      properties:
        id:
          type: string
          example: "msg_1234567890"
        conversationId:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        senderId:
          type: string
          example: "my_chat_app_alice_123"
        type:
          type: string
          enum: [TEXT, IMAGE, DOCUMENT, AUDIO, CALL]
          example: "TEXT"
        content:
          type: string
          nullable: true
          example: "Hey team, when is the next meeting?"
        metadata:
          type: string
          nullable: true
          description: JSON stringified metadata
          example: '{"priority":"high"}'
        createdAt:
          type: string
          format: date-time
          example: "2024-01-19T12:00:00Z"

    Call:
      type: object
      properties:
        id:
          type: string
          example: "call_abc123"
        conversationId:
          type: string
          example: "550e8400-e29b-41d4-a716-446655440000"
        callerId:
          type: string
          example: "my_chat_app_alice_123"
        status:
          type: string
          enum: [ONGOING, ENDED]
          example: "ONGOING"
        startedAt:
          type: string
          format: date-time
          example: "2024-01-19T12:05:00Z"
        endedAt:
          type: string
          format: date-time
          nullable: true
          example: null

security:
  - UserIdHeader: []
    AppIdHeader: []

paths:
  /chat/connect:
    post:
      summary: Connect User
      description: Registers or updates a user in the chat system. Returns the user object.
      security: [] # No auth headers needed for connect technically in this logic, but good practice
      tags:
        - Chat Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectPayload'
      responses:
        '200':
          description: User connected successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                    example: "Connected successfully"

  /chat/conversations:
    post:
      summary: Create Conversation
      description: Creates a new direct or group conversation.
      tags:
        - Conversations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConversationPayload'
      responses:
        '200':
          description: Conversation created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Conversation'
    get:
      summary: Get Conversations
      description: Retrieves a list of conversations for the authenticated user, including last message and unread count.
      tags:
        - Conversations
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'

  /chat/conversations/{id}/messages:
    post:
      summary: Send Message
      description: Sends a message to a specific conversation.
      tags:
        - Messages
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Conversation ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessagePayload'
      responses:
        '200':
          description: Message sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Message'
    get:
      summary: Get Messages
      description: Retrieves messages for a conversation with pagination support.
      tags:
        - Messages
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Conversation ID
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
          description: Number of messages to retrieve
        - in: query
          name: cursor
          schema:
            type: string
          description: Message ID to start fetching from (for pagination)
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'

  /chat/groups/{id}/participants:
    post:
      summary: Add Participants
      description: Adds users to an existing group conversation. Only admins can perform this.
      tags:
        - Participants
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Group Conversation ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddParticipantPayload'
      responses:
        '200':
          description: Participants added
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                  message:
                    type: string
                    example: "Participants added"

  /chat/groups/{id}/participants/{userId}:
    delete:
      summary: Remove Participant
      description: Removes a user from a group conversation. Only admins can perform this.
      tags:
        - Participants
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Group Conversation ID
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user to remove
      responses:
        '200':
          description: Participant removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                  message:
                    type: string
                    example: "Participant removed"

  /chat/upload:
    post:
      summary: Upload File
      description: Uploads a file and returns a URL.
      tags:
        - Media
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UploadResponse'

  /chat/calls/{id}/token:
    get:
      summary: Get LiveKit Token
      description: Generates a token to join a voice/video call in a conversation.
      tags:
        - Calls
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Conversation ID
      responses:
        '200':
          description: Token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

  /chat/conversations/{id}/call:
    post:
      summary: Start Call
      description: Initiates a call in a conversation.
      tags:
        - Calls
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Conversation ID
      responses:
        '200':
          description: Call started
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Call'

  /chat/calls/{id}/end:
    post:
      summary: End Call
      description: Marks a call as ended.
      tags:
        - Calls
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Call ID
      responses:
        '200':
          description: Call ended
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Call'
                    description: The call object with status ENDED and endedAt populated
